version: '3'


services:

    choochoo:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        privileged: true
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            - ./software:/software
            - /media/usb:/media/usb



        command: ["python", "software/play.py"]
