version: '2'


volumes:
  config: {}
  music: {}


services:

  conductor:
    build:
      context: .
      dockerfile: Dockerfile.conductor
    container_name: conductor
    privileged: true
    volumes:
      - config:/config:ro
      - music:/music
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem
    cap_add:
      - SYS_RAWIO
    depends_on:
      - rtc
    restart: 'always'


  rtc:
    build:
      context: .
      dockerfile: Dockerfile.rtc
    container_name: rtc
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
    cap_add:
      - SYS_RAWIO
    restart: 'no'


  music_vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
    privileged: true
    volumes:
      - config:/config:ro
      - music:/music
    restart: 'no'


  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - config:/config:ro
      - music:/music
    ports:
      - 80:3000
    restart: 'always'

  
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    restart: 'always'
